/** Longest prefixes first so "Gulf of " wins over a shorter "Gulf ". */
export const PREFIXES = [
  { prefix: "National Forest ", label: "National Forest America" },
  { prefix: "State Forest ", label: "State Forest America" },
  { prefix: "Republic of ", label: "Republic of America" },
  { prefix: "Interstate ", label: "Interstate America" },
  { prefix: "Expressway ", label: "Expressway America" },
  { prefix: "Forest of ", label: "Forest of America" },
  { prefix: "Boulevard ", label: "Boulevard America" },
  { prefix: "Peninsula ", label: "Peninsula America" },
  { prefix: "Reservoir ", label: "Reservoir America" },
  { prefix: "Turnpike ", label: "Turnpike America" },
  { prefix: "Causeway ", label: "Causeway America" },
  { prefix: "Mountain ", label: "Mountain America" },
  { prefix: "National ", label: "National America" },
  { prefix: "Isle of ", label: "Isle of America" },
  { prefix: "Gulf of ", label: "Gulf of America" },
  { prefix: "Highway ", label: "Highway America" },
  { prefix: "Parkway ", label: "Parkway America" },
  { prefix: "Freeway ", label: "Freeway America" },
  { prefix: "Channel ", label: "Channel America" },
  { prefix: "Glacier ", label: "Glacier America" },
  { prefix: "Plateau ", label: "Plateau America" },
  { prefix: "Islands ", label: "Islands America" },
  { prefix: "Prairie ", label: "Prairie America" },
  { prefix: "Beltway ", label: "Beltway America" },
  { prefix: "Sea of ", label: "Sea of America" },
  { prefix: "Bay of ", label: "Bay of America" },
  { prefix: "United ", label: "United America" },
  { prefix: "Harbor ", label: "Harbor America" },
  { prefix: "Canyon ", label: "Canyon America" },
  { prefix: "Desert ", label: "Desert America" },
  { prefix: "Valley ", label: "Valley America" },
  { prefix: "Island ", label: "Island America" },
  { prefix: "Strait ", label: "Strait America" },
  { prefix: "Stream ", label: "Stream America" },
  { prefix: "Avenue ", label: "Avenue America" },
  { prefix: "Street ", label: "Street America" },
  { prefix: "Tunnel ", label: "Tunnel America" },
  { prefix: "Bridge ", label: "Bridge America" },
  { prefix: "Circle ", label: "Circle America" },
  { prefix: "Forest ", label: "Forest America" },
  { prefix: "Mount ", label: "Mount America" },
  { prefix: "North ", label: "North America" },
  { prefix: "South ", label: "South America" },
  { prefix: "Great ", label: "Great America" },
  { prefix: "Saint ", label: "Saint America" },
  { prefix: "Woods ", label: "Woods America" },
  { prefix: "River ", label: "River America" },
  { prefix: "Creek ", label: "Creek America" },
  { prefix: "Brook ", label: "Brook America" },
  { prefix: "Canal ", label: "Canal America" },
  { prefix: "Inlet ", label: "Inlet America" },
  { prefix: "Ocean ", label: "Ocean America" },
  { prefix: "Sound ", label: "Sound America" },
  { prefix: "Trail ", label: "Trail America" },
  { prefix: "Route ", label: "Route America" },
  { prefix: "Drive ", label: "Drive America" },
  { prefix: "Alley ", label: "Alley America" },
  { prefix: "Point ", label: "Point America" },
  { prefix: "Lake ", label: "Lake America" },
  { prefix: "East ", label: "East America" },
  { prefix: "West ", label: "West America" },
  { prefix: "Fort ", label: "Fort America" },
  { prefix: "Port ", label: "Port America" },
  { prefix: "Cape ", label: "Cape America" },
  { prefix: "Road ", label: "Road America" },
  { prefix: "Lane ", label: "Lane America" },
  { prefix: "New ", label: "New America" },
  { prefix: "The ", label: "The America" },
  { prefix: "Way ", label: "Way America" },
];

/** Leading space + type, longest first. New York City → New America City; Hudson River → America River. */
export const SUFFIXES = [
  " National Forest",
  " State Forest",
  " Expressway",
  " Interstate",
  " Boulevard",
  " Peninsula",
  " Reservoir",
  " Mountains",
  " Township",
  " Turnpike",
  " Causeway",
  " Mountain",
  " Parkway",
  " Freeway",
  " Highway",
  " Channel",
  " Glacier",
  " Plateau",
  " Islands",
  " Prairie",
  " Beltway",
  " Borough",
  " Village",
  " County",
  " Parish",
  " Harbor",
  " Canyon",
  " Desert",
  " Valley",
  " Island",
  " Strait",
  " Stream",
  " Avenue",
  " Street",
  " Tunnel",
  " Bridge",
  " Circle",
  " Forest",
  " Woods",
  " River",
  " Creek",
  " Brook",
  " Canal",
  " Inlet",
  " Ocean",
  " Sound",
  " Trail",
  " Route",
  " Drive",
  " Town",
  " City",
  " Road",
  " Lane",
  " Point",
  " Falls",
  " Ridge",
  " Marsh",
  " Swamp",
  " Alley",
  " Park",
  " Way",
];
